# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'Acordei-Transparencia' do
pod 'FMDB'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'XYPieChart'
end

target 'Acordei-TransparenciaTests' do
pod 'FMDB'
end

